---
# tasks file for beacon
#

- name: Set up docker
  ansible.builtin.import_role:
    name: geerlingguy.docker
  vars:
     docker_users:
      - centos

- name: Ensure python-requests is available
  ansible.builtin.package:
    name: "python3-requests"
    state: present

- name: Ensure docker network for the deployment exists
  community.docker.docker_network:
    name: "{{ shared_network_name }}"
    state: present

# This task will set
- name: Set up postgres
  ansible.builtin.include_tasks: "setup-postgres.yml"

- name: Set up beacon-python
  ansible.builtin.include_tasks: "setup-beacon-python.yml"
