---
# tasks file for beacon
#
---
# encountered at https://github.com/usegalaxy-eu/ansible-traefik/blob/main/tasks/main.yml#L3
- name: Include EL9 python workaround
  include_tasks: ansible-python.yml
  when: ansible_os_family == "RedHat"

- name: Set up docker
  ansible.builtin.import_role:
    name: geerlingguy.docker
  vars:
     docker_users:
      - centos

- name: Ensure python-requests is available
  ansible.builtin.package:
    name: "python3-requests"
    state: present
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == '9'

- name: Ensure docker network for the deployment exists
  community.docker.docker_network:
    name: "{{ shared_network_name }}"
    state: present

# This task will set
- name: Set up postgres
  ansible.builtin.include_tasks: "setup-postgres.yml"

- name: Set up beacon-python
  ansible.builtin.include_tasks: "setup-beacon-python.yml"
